import { Poppins } from "next/font/google";
import "./globals.css";
import "./style.css";
import Navigation from "@/components/Navigation/Navigation";
import MenuBar from "@/components/MenuBar/MenuBar";
import MobileView from "@/components/MobileView/MobileView";
import { ToastContainer } from "react-toastify";
import AOS from 'aos';
import 'aos/dist/aos.css';
import AOSInit from "@/components/util/AosInit";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-800`}>
        <Navigation />
        <MobileView />
        <div className="lg:block hidden">
          <div className=" w-screen  grid grid-cols-[0.25fr_0.75fr] mt-2">
            <div className="bg-slate-500 rounded-lg"><MenuBar /></div>
            <div className="p-5 h-[860px] overflow-y-scroll ">
              {children}
              
            </div>
          </div>

        </div>
        <ToastContainer/>
        <AOSInit/>
      </body>
    </html>
  );
}
